<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
	String contextPath = request.getContextPath();
%>
<!DOCTYPE html>
<html>
<head>
<title></title>
<jsp:include page="../../../../inc.jsp"></jsp:include>
<script type="text/javascript">

</script>
</head>
<body>
	<form method="post" class="form">
		<fieldset>
			<legend>基本信息</legend>
			<table class="table" style="width: 100%;">
				<tr>	
					<th>主键</th>
					<td>
						${bean.bd_id}
					</td>
				</tr>	
				<tr>	
					<th>编码</th>
					<td>
						${bean.bd_code}
					</td>
				</tr>	
				<tr>	
					<th>名称</th>
					<td>
						${bean.bd_name}
					</td>
				</tr>	
				<tr>	
					<th>排序</th>
					<td>
						${bean.bd_order}
					</td>
				</tr>	
				<tr>	
					<th>父节点PID</th>
					<td>
						${bean.bd_pid}
					</td>
				</tr>	
				<tr>	
					<th>字典类型</th>
					<td>
						${bean.bd_datatypeid}
					</td>
				</tr>	
				<tr>	
					<th>部门</th>
					<td>
						${bean.bd_org}
					</td>
				</tr>	
				<tr>	
					<th>描述</th>
					<td>
						${bean.bd_des}
					</td>
				</tr>	
				<tr>	
					<th>状态</th>
					<td>
						${bean.bd_status}
					</td>
				</tr>	
				<tr>	
					<th></th>
					<td>
						${bean.def1}
					</td>
				</tr>	
				<tr>	
					<th></th>
					<td>
						${bean.def2}
					</td>
				</tr>	
				<tr>	
					<th></th>
					<td>
						${bean.bd_dr}
					</td>
				</tr>	
				<tr>	
					<th></th>
					<td>
						${bean.bd_ts}
					</td>
				</tr>	
				<tr>	
					<th></th>
					<td>
						${bean.bd_version}
					</td>
				</tr>	
			</table>
		</fieldset>
	</form>
</body>
</html>